version: "1.0"
info:
  model: int-scaffold
packages:
- name: Kvv_3003_FedDevProject
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: TPP_services_in_FCS
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
  wpmVersion: latest
services:
- serviceName: project.kvv_3003_feddev.integrations:AlertsCRTandERT
  packages:
  - name: Kvv_3003_FedDevProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 12.0.0.0.774
- serviceName: project.kvv_3003_feddev.integrations:Sum
  packages:
  - name: Kvv_3003_FedDevProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 12.0.0.0.774
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 12.0.0.0.774
- serviceName: project.kvv_3003_feddev.integrations:deepclonetest
  packages:
  - name: Kvv_3003_FedDevProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 12.0.0.0.774
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 12.0.0.0.774
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 12.0.0.0.774
configurationVariables:
  jdbc.Embedded-Database-Pool.waitingThread: "0"
  jdbcfunc.ISDashboardStats.failFastMode: false
  jdbc.Embedded-Database-Pool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/Embedded-Database-Pool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbcfunc.ISInternal.failFastMode: true
  jdbc.Embedded-Database-Pool.maxConns: "10"
  jdbc.Embedded-Database-Pool.spyenabled: "false"
  jdbcfunc.Xref.failFastMode: true
  jdbcfunc.ISDashboardStats.connPoolAlias: Embedded-Database-Pool
  jdbc.Embedded-Database-Pool.expireTime: "60000"
  jdbc.Embedded-Database-Pool.poolThreshold: "0"
  jdbcfunc.Xref.connPoolAlias: Embedded-Database-Pool
  jdbc.Embedded-Database-Pool.userid: APP
  jdbc.Embedded-Database-Pool.useSSL: "false"
  jdbcfunc.ISInternal.connPoolAlias: Embedded-Database-Pool
  jdbc.Embedded-Database-Pool.password: "{AES}Zcw2EXTJgNDVmVzJO2Y3Bw=="
  jdbc.Embedded-Database-Pool.minConns: "0"
  jdbc.Embedded-Database-Pool.driverAlias: Embedded Database Driver
  jdbc.Embedded-Database-Pool.spyparms: SpyAttributes=(log=(file)logs/spy/Embedded-Database-Pool.log;logTName=yes;timestamp=yes)
  jdbc.Embedded-Database-Pool.dbURL: jdbc:derby:embedded;create=true
  jdbc.Embedded-Database-Pool.snoopenabled: "false"
