version: "1.0"
projectName: Kvv_3003_FedDevProject
runtimes:
- runtimeAlias: Cloud Designtime
  assets:
  - name: cdtWorkflow
    type: workflow
    uid: fl652ef8b934ef47b88f06ae2415908333
    stepId: a0
    reference: project.kvv_3003_feddev.integrations:Sum
  - name: cdtWorkflow
    type: workflow
    uid: fl652ef8b934ef47b88f06ae2415908333
    stepId: a1
    reference: services:add3Ints
  - name: cdtWorkflow
    type: workflow
    uid: fl652ef8b934ef47b88f06ae2415908333
    stepId: a2
    reference: project.kvv_3003_feddev.integrations:deepclonetest
  - name: cdtWorkflow
    type: workflow
    uid: fl652ef8b934ef47b88f06ae2415908333
    stepId: a3
    reference: project.kvv_3003_feddev.integrations:tppdaf
  - name: 5secWorkflow
    type: workflow
    uid: flcd200da93bf9468ba9a6ba5144085f9c
    stepId: a0
    reference: SIQA_TimeoutTest:delayfor5Sec
  - name: 180secWorkflow
    type: workflow
    uid: fl6ca9b46090444407bf27b731be042de7
    stepId: a0
    reference: SIQA_TimeoutTest:delayfor180Sec
  - name: fld_124597485_stage00.projects.fl10f342404a1a41778592861963d95503.integrations:tppfcs
    type: flow
    stepId: /0
    reference: fld_124597485_stage00.projects.fl10f342404a1a41778592861963d95503.WmPackageServiceProvider.SIQACloudStreamsTests:connetorOperations
  - name: restTest
    type: REST
    path: /drt
    action: POST
    reference: fld_124597485_stage00.projects.fl10f342404a1a41778592861963d95503.WmPackageServiceProvider.services:add3Ints
  - name: restTest
    type: REST
    path: /dafdrt
    action: POST
    reference: fld_124597485_stage00.projects.fl10f342404a1a41778592861963d95503.WmPackageServiceProvider.project.kvv_3003_feddev.integrations:Sum
- runtimeAlias: kvv_3003_FedDev
  assets:
  - name: ertWorkflow
    type: workflow
    uid: fl20c06446bd23450caba28e937391713f
    stepId: a0
    reference: project.kvv_3003_feddev.integrations:Sum
  - name: ertWorkflow
    type: workflow
    uid: fl20c06446bd23450caba28e937391713f
    stepId: a1
    reference: services:add3Ints
  - name: ertWorkflow
    type: workflow
    uid: fl20c06446bd23450caba28e937391713f
    stepId: a2
    reference: project.kvv_3003_feddev.integrations:deepclonetest
  - name: ertWorkflow
    type: workflow
    uid: fl20c06446bd23450caba28e937391713f
    stepId: a3
    reference: project.kvv_3003_feddev.integrations:tppdaf
  - name: 5secWorkflow
    type: workflow
    uid: flcd200da93bf9468ba9a6ba5144085f9c
    stepId: a1
    reference: SIQA_TimeoutTest:delayfor5Sec
  - name: 180secWorkflow
    type: workflow
    uid: fl6ca9b46090444407bf27b731be042de7
    stepId: a1
    reference: SIQA_TimeoutTest:delayfor180Sec
  - name: fld_124597485_stage00.projects.fl10f342404a1a41778592861963d95503.integrations:tppfcs
    type: flow
    stepId: /1
    reference: fld_124597485_stage00.projects.fl10f342404a1a41778592861963d95503.WmPackageServiceProvider.SIQACloudStreamsTests:connetorOperations
  - name: fld_124597485_stage00.projects.fl10f342404a1a41778592861963d95503.integrations:tppfcs
    type: flow
    stepId: /2
    reference: fld_124597485_stage00.projects.fl10f342404a1a41778592861963d95503.WmPackageServiceProvider.SIQAJDBCAdapterTests.adapterServices:getData
  - name: restTest
    type: REST
    path: /ert
    action: POST
    reference: fld_124597485_stage00.projects.fl10f342404a1a41778592861963d95503.WmPackageServiceProvider.services:add3Ints
